### ISSUE TITLE
Is the tie to cinch at 2.0.3 necessary?

### ISSUE THREAD

**Issue by mooreniemi** [britishtea/cinch-authentication#2]
I get conflicts if I try to use your gem as a dependency in my own, because yours is tied to an older version of Cinch.

**Comment by britishtea** [comment]
Sorry this took so long. I've loosened the dependency requirement in https://github.com/britishtea/cinch-authentication/commit/68fc47b337fc97835416ae15cac7903810fd3312. I've also pushed a new build to rubygems.org (version `0.1.1`).

If you find any problems, please let me know.

**Comment by mooreniemi** [comment]
thanks!
